### ISSUE TITLE
authentication certificate expired

### ISSUE THREAD

**Issue by skynet** [Paul-Reed/StartSSL#1]
The "authentication certificate" that we use to log in to StartSSL's control panel seems to expire after 1 year. 
![1](https://cloud.githubusercontent.com/assets/139233/10417000/41c3b890-6ffb-11e5-813e-c44aa1d5ef1f.PNG)
![2](https://cloud.githubusercontent.com/assets/139233/10416999/41c2a0b8-6ffb-11e5-952e-4ddd24901ece.PNG)

I had to register again and here it is:
![3](https://cloud.githubusercontent.com/assets/139233/10417049/7700526a-6ffc-11e5-9f03-fc19f888760d.PNG)

**Comment by Paul-Reed** [comment]
Validity last 350 days, see [StartSSL's FAQ](https://www.startssl.com/?app=25#20)

**Comment by skynet** [comment]
It does, but during this period I accumulate certs in the Control Panel, and I need to be able to retrieve them. Did you understand my problem here?

**Comment by Paul-Reed** [comment]
Well contact StartSSL and ask them for help. Probably like you, I'm also not familiar with their processes either.

**Comment by skynet** [comment]
I did. Waiting for a response.
